global:
  scrape_interval: 10s
  external_labels:
    environment: lab

scrape_configs:
  - job_name: "dynamic-targets"
    file_sd_configs:
      - files:
          - '/etc/prometheus/sd/targets.json'
        refresh_interval: 5s