{
 "title": "demo-api",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(demo_http_requests_total,endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Taux de requêtes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(demo_http_requests_total{endpoint=~\"$endpoint\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio d'erreurs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(demo_http_requests_total{status=~\"5..\", endpoint=~\"$endpoint\"}[5m])) / sum(rate(demo_http_requests_total{endpoint=~\"$endpoint\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(demo_http_request_duration_seconds_bucket{endpoint=~\"$endpoint\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}